include: package:very_good_analysis/analysis_options.3.0.1.yaml

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.gr.dart]

  strong-mode:
    implicit-casts: false

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    library_private_types_in_public_api: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    

